sudo: false
language: go
git:
    depth: 1
install: 
    mkdir $HOME/src
    cd $HOME/src
    git clone https://github.com/gohugoio/hugo.git
    cd hugo
    go install
script:
    - git submodule init 
    - hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $token
    on:
        branch: master
    local_dir: public
    repo: cloudjjcc/cloudjjcc.github.io
    target_branch: master
    email: cloudjjcc@gmail.com
    name: cloudjjcc